<p><a href="<?php echo $this->url(array('controller'=>'users','action'=>'nuevo'));?>">Nuevo Usuario</a></p>
<?php if(isset($this->users)): ?>
<table>
	<caption>manti user</caption>
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Email</th>
			<th>web</th>
			<th>Estado</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->users as $usr):?>
		<tr>
			<td><?php echo $usr['name']; ?></td>
			<td><?php echo $usr['email']; ?></td>
			<td><?php echo $usr['web']; ?></td>
			<td><?php echo $usr['status']; ?></td>
			<td>
			<a href="<?php echo $this->url(array('controller'=>'users','action'=>'editar', 'id'=>$usr['id']));?>">Edit</a>
			</td>
			<td><a title="" onclick="eliminar(1);">ELiminar</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php endif; ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script>
function eliminar(n)
{
	alert(n);
}
</script>